<a href="https://colab.research.google.com/github/AlexandraRawrrr/python_for_ds_tasks/blob/main/Copy_of_hw_10_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')


df = pd.read_csv('/content/drive/MyDrive/supermarket_sales.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [3]:
df.groupby('Branch')['gross income'].sum().sort_values(ascending=False)

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [4]:
df.groupby('City')['gross income'].sum().sort_values(ascending=False).round(2)

City
Naypyitaw    5265.18
Yangon       5057.16
Mandalay     5057.03
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [8]:
invoices_by_category = pd.crosstab(df['Branch'], df['Product line'])
print(invoices_by_category)

Product line  Electronic accessories  Fashion accessories  Food and beverages  \
Branch
A                                 60                   51                  58
B                                 55                   62                  50
C                                 55                   65                  66

Product line  Health and beauty  Home and lifestyle  Sports and travel
Branch
A                            47                  65                 59
B                            53                  50                 62
C                            52                  45                 45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [10]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

# **Що найчастіше купують?**

In [11]:
df.groupby(['Customer type', 'Product line'])['Quantity'].sum().unstack()

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Customer type,,,,,,
Member,429,439,506,428,490,493
Normal,542,463,446,426,421,427

In [12]:
df.groupby(['Customer type', 'Product line'])['Quantity'].sum().groupby(level=0).idxmax()

Customer type
Member        (Member, Food and beverages)
Normal    (Normal, Electronic accessories)
Name: Quantity, dtype: object

За цими даними можу запропонувати спеціальні діскаунти для мемберів в категоріях, в яких більш за все покупок, а для нормальних - систему залучення до програми лояльності, які дають чкісь корисні бенефіти.

# **Коли купують найбільше?**

In [14]:
df['Date'] = pd.to_datetime(df['Date'])
df['Day'] = df['Date'].dt.day_name()

In [16]:
df.groupby('Day')['Quantity'].mean().sort_values(ascending=False).round(2)

Day
Sunday       5.85
Saturday     5.60
Wednesday    5.59
Thursday     5.47
Tuesday      5.46
Friday       5.45
Monday       5.10
Name: Quantity, dtype: float64

Запускати спеціальні акції або пропозиції у дні, коли найменше продажів за нашими даними, тобто у поеділок та п'ятницю, а також оптимізувати працю у дні з найбільшою загруженістю.

# **Наскільки клієнти задоволені тим, що вони купують?**

In [21]:
avg_rating_by_branch = df.groupby('Branch')['Rating'].mean().sort_values(ascending=False).round(2)
print(avg_rating_by_branch)

Branch
C    7.07
A    7.03
B    6.82
Name: Rating, dtype: float64

In [20]:
avg_rating_by_product = df.groupby('Product line')['Rating'].mean().sort_values(ascending=False).round(2)
print(avg_rating_by_product)

Product line
Food and beverages        7.11
Fashion accessories       7.03
Health and beauty         7.00
Electronic accessories    6.92
Sports and travel         6.92
Home and lifestyle        6.84
Name: Rating, dtype: float64

In [23]:
avg_rating_combo = df.groupby(['Branch', 'Product line'])['Rating'].mean().unstack().round(2)
print(avg_rating_combo)

Product line  Electronic accessories  Fashion accessories  Food and beverages  \
Branch
A                               6.91                 6.88                7.25
B                               7.12                 6.72                6.99
C                               6.75                 7.44                7.08

Product line  Health and beauty  Home and lifestyle  Sports and travel
Branch
A                           6.9                6.93               7.26
B                           7.1                6.52               6.51
C                           7.0                7.06               7.03

За цими ланими можна побасити степінь задоволеності клієнтами конкретних товарів. Можливо перегляд асортименту або постачальників.
Якщо низький рейтинг філії - варто переглянути рівень сервісу (швидкість, кваліфікованість або чистота).